# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from typing import Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel

from ..capability import BusinessSchema as BusinessSchema_1
from ..capability import PlatformSchema as PlatformSchema_1


class IdentityLinkingCapability(RootModel[Any]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Any = Field(..., title="Identity Linking Capability")
    """
    Schema for authenticating and establishing verified connections between platforms and businesses.
    """


class IdentityScope(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: str = Field(
        ...,
        pattern="^[a-zA-Z0-9][a-zA-Z0-9_\\-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_\\-]*)*\\.scopes\\.[a-zA-Z0-9][a-zA-Z0-9_\\-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_\\-]*)*$",
    )


class IdentityScopes(RootModel[list[IdentityScope]]):
    """
    A custom UCP annotation placed at the root of a capability schema to declare the OAuth 2.0 scopes required to operate that capability. Scopes MUST use reverse DNS dot notation to prevent namespace collisions (e.g., 'dev.ucp.shopping.scopes.checkout_session' for UCP-defined scopes, 'com.example.scopes.my_capability' for third-party scopes). Platforms collect this annotation from every capability in the finalized negotiated intersection and use the union as the authorization scope set. This annotation is intentionally a plain JSON array so it is ignored by standard JSON Schema validators — it carries semantic meaning only to UCP-aware tooling. Absence of this annotation on a capability schema means that capability requires no dedicated scope.
    """

    model_config = ConfigDict(
        frozen=True,
    )
    root: list[IdentityScope] = Field(
        ..., min_length=1, title="Identity Scopes Annotation"
    )
    """
    A custom UCP annotation placed at the root of a capability schema to declare the OAuth 2.0 scopes required to operate that capability. Scopes MUST use reverse DNS dot notation to prevent namespace collisions (e.g., 'dev.ucp.shopping.scopes.checkout_session' for UCP-defined scopes, 'com.example.scopes.my_capability' for third-party scopes). Platforms collect this annotation from every capability in the finalized negotiated intersection and use the union as the authorization scope set. This annotation is intentionally a plain JSON array so it is ignored by standard JSON Schema validators — it carries semantic meaning only to UCP-aware tooling. Absence of this annotation on a capability schema means that capability requires no dedicated scope.
    """


class Mechanism(BaseModel):
    """
    Base definition for any authentication mechanism. The 'type' field discriminates between known mechanism schemas (e.g., oauth2). Unknown types pass through with only the base requirement, enabling forward-compatible extensibility. Note: this open base schema does not enforce field requirements for known types — use $defs/oauth2 directly to validate an oauth2 mechanism object explicitly.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    type: str
    """
    The mechanism type discriminator. Known values: 'oauth2'. Specific mechanism schemas constrain this to a constant value.
    """


class Oauth2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["oauth2"]
    """
    OAuth 2.0 authentication mechanism.
    """
    issuer: AnyUrl
    """
    The authorization server URL, supporting RFC 8414 discovery.
    """
    discovery_endpoint: AnyUrl | None = None
    """
    Optional explicit URI to the authorization server's metadata (e.g., `https://auth.merchant.example.com/.well-known/openid-configuration`). If omitted, platforms construct discovery paths based on the `issuer`.
    """


class PlatformSchema(PlatformSchema_1):
    model_config = ConfigDict(
        extra="allow",
    )


class Config(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    supported_mechanisms: list[Mechanism] = Field(..., min_length=1)


class BusinessSchema(BusinessSchema_1):
    model_config = ConfigDict(
        extra="allow",
    )
    config: Config
