# Copyright 2026 UCP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen
# pylint: disable=all
# pyformat: disable

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .. import ucp as ucp_1
from .types import context as context_1
from .types import input_correlation, message
from .types import signals as signals_1
from .types.product import Product as Product_1
from .types.variant import Variant


class CatalogLookup(BaseModel):
    """
    Product/variant lookup by identifier capability.
    """

    model_config = ConfigDict(
        extra="allow",
    )


class LookupVariant(Variant):
    """
    Variant with required correlation metadata for lookup responses.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    inputs: list[input_correlation.InputCorrelation] = Field(..., min_length=1)
    """
    Which request identifiers resolved to this variant, and how. Each entry maps a request ID to its match type.
    """


class LookupRequest(BaseModel):
    """
    Request body for catalog lookup.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    ids: list[str] = Field(..., min_length=1)
    """
    Identifiers to lookup. Implementations MUST support product ID and variant ID; MAY support secondary identifiers (SKU, handle, etc.).
    """
    context: context_1.Context | None = None
    signals: signals_1.Signals | None = None


class Product(Product_1):
    model_config = ConfigDict(
        extra="allow",
    )
    variants: list[LookupVariant] | None = None


class LookupResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    ucp: ucp_1.ResponseCatalogSchema
    products: list[Product]
    """
    Products matching the requested identifiers. May contain fewer items if some identifiers not found, or more if identifiers match multiple products.
    """
    messages: list[message.Message] | None = None
    """
    Errors, warnings, or informational messages about the requested items.
    """
